name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Build JAR
        run: mvn clean package

      - name: Docker Build and Push
        env:
          ECR_REGISTRY: ec2-54-253-232-51.ap-southeast-2.compute.amazonaws.com
          ECR_REPOSITORY: attendance-reports
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA .
          docker login -u AWS -p $(aws ecr get-login-password) $ECR_REGISTRY
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$GITHUB_SHA
